name: Run Playlist Script

on:
  schedule:
    - cron: '0 0 * * *'  # A mezzanotte UTC
  workflow_dispatch: # Trigger manuale

jobs:
  run-script:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # Serve per pushare i file
      issues: write     # Se vuoi anche scrivere nelle issue

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'

    - name: Run Movie Playlist PHP script
      run: php php/create_movie_playlist.php
      env:
        SECRET_API_KEY: ${{ secrets.SECRET_API_KEY }}
        
    #- name: Run Movie Playlist PHP script
    #  run: php php/create_movie_playlist_full.php
    #  env:
    #    SECRET_API_KEY: ${{ secrets.SECRET_API_KEY }}

    - name: Run TV Playlist PHP script
      run: php php/create_tv_playlist.php
      env:
        SECRET_API_KEY: ${{ secrets.SECRET_API_KEY }}
        
    #- name: Run TV Playlist PHP script
    #  run: php php/create_tv_playlist_full.php
    #  env:
    #    SECRET_API_KEY: ${{ secrets.SECRET_API_KEY }}
        
    - name: Commit and Push to Public Repository
      run: |
        git config user.name "actions-user"
        git config user.email "actions@github.com"
        git add playlist.m3u8 playlist.json tv_playlist.json
        git commit -m "Update Playlists" || echo "No changes to Playlists"
        git pull --rebase origin main || true
        git push origin main
